# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phlex-sinatra` gem.
# Please instead update this file by running `bin/tapioca gem phlex-sinatra`.


# source://phlex-sinatra//lib/phlex/sinatra/version.rb#3
module Phlex
  class << self
    # source://phlex/2.2.1/lib/phlex.rb#28
    def __expand_attribute_cache__(file_path); end

    # source://phlex/2.2.1/lib/phlex.rb#36
    def html(&block); end

    # source://phlex/2.2.1/lib/phlex.rb#52
    def svg(&block); end
  end
end

class Phlex::SGML
  include ::Phlex::Sinatra::SGMLOverrides
end

# source://phlex-sinatra//lib/phlex/sinatra/version.rb#4
module Phlex::Sinatra
  # @raise [TypeError]
  #
  # source://phlex-sinatra//lib/phlex-sinatra.rb#32
  def phlex(obj, content_type: T.unsafe(nil), layout: T.unsafe(nil), layout_engine: T.unsafe(nil), stream: T.unsafe(nil)); end
end

# source://phlex-sinatra//lib/phlex-sinatra.rb#10
class Phlex::Sinatra::ArgumentError < ::Phlex::Sinatra::Error; end

# source://phlex-sinatra//lib/phlex-sinatra.rb#9
class Phlex::Sinatra::Error < ::StandardError; end

# source://phlex-sinatra//lib/phlex-sinatra.rb#22
module Phlex::Sinatra::SGMLOverrides
  # source://phlex-sinatra//lib/phlex-sinatra.rb#23
  def helpers; end

  # source://phlex-sinatra//lib/phlex-sinatra.rb#27
  def url(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-sinatra//lib/phlex-sinatra.rb#12
class Phlex::Sinatra::TypeError < ::Phlex::Sinatra::Error
  # @return [TypeError] a new instance of TypeError
  #
  # source://phlex-sinatra//lib/phlex-sinatra.rb#15
  def initialize(obj); end
end

# source://phlex-sinatra//lib/phlex-sinatra.rb#13
Phlex::Sinatra::TypeError::MAX_SIZE = T.let(T.unsafe(nil), Integer)

# source://phlex-sinatra//lib/phlex/sinatra/version.rb#5
Phlex::Sinatra::VERSION = T.let(T.unsafe(nil), String)

class Sinatra::Application < ::Sinatra::Base
  include ::Phlex::Sinatra
end
