AllCops:
    NewCops: enable

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Lint/MissingSuper:
  AllowedParentClasses: [Phlex::HTML]

### Disabled ###
Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false
