AllCops:
    NewCops: enable

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Lint/MissingSuper:
  AllowedParentClasses: [Phlex::HTML]

### Disabled ###
Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false
